FROM ghcr.io/pnpm/pnpm:11 AS base

LABEL com.beemovr.description="https://github.com/soobinrho/GoodLifeFarms"
LABEL com.beemovr.maintainer="Soobin Rho <soobin@nsustain.com>"

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1

RUN pnpm runtime set node 22 -g

WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm run build

CMD ["node", ".next/standalone/server.js"]
